function templates = pipelineTemplates()
% PIPELINETEMPLATES  Return all built-in pipeline templates.
%
%   templates = PIPELINETEMPLATES() returns a struct array where each
%   element describes one template:
%
%     .name      - display name (shown in the picker dialog)
%     .steps     - cell array of step label strings; must match stepRegistry
%                  names exactly (and therefore the StepsListBox items)
%     .overrides - cell array of structs, one per step, containing raw
%                  EEGLAB parameter key→value overrides to apply on top of
%                  the step defaults.  Use struct() for no overrides.
%
%   Adding a template: append one block below following the existing
%   pattern and ensure every step name matches an entry in stepRegistry.
%
%   Pipeline designs follow published best practices:
%     TMS-EEG  — Rogasch et al. 2017 (NeuroImage), TESA toolbox documentation
%     Resting  — Bigdely-Shamlo et al. 2015 (PREP), EEGLAB tutorials
%     Minimal  — EEGLAB standard cleaning recommendations
%
%   See also: stepRegistry, nestapp

templates = struct('name', {}, 'steps', {}, 'overrides', {});

%% ---- TMS-EEG / TEP (TESA) -----------------------------------------------
% Two-round ICA pipeline per Rogasch et al. 2017 and the TESA toolbox
% documentation.  Key decisions:
%   - Average re-reference applied after channel interpolation so that all
%     surviving channels contribute equally to the reference (Rogasch 2017).
%   - Two separate FastICA + compselect passes: Round 1 targets TMS-evoked
%     muscle artifact and electrode noise; Round 2 targets blink, eye
%     movement, and residual muscle after the cleaner signal is available.
%   - Baseline correction and bad-epoch rejection come last so that the full
%     artefact-removal chain is complete before any data is discarded.
t = blankTemplate();
t.name = 'TMS-EEG / TEP (TESA)';
t.steps = { ...
    'Load Data', ...
    'Load Channel Location', ...
    'Remove un-needed Channels', ...
    'Find TMS Pulses (TESA)', ...
    'Remove TMS Artifacts (TESA)', ...
    'Interpolate Missing Data (TESA)', ...
    'Re-Sample', ...
    'Frequency Filter (TESA)', ...
    'Epoching', ...
    'Remove Bad Channels', ...
    'Interpolate Channels', ...
    'Re-Reference', ...
    'Run TESA ICA', ...
    'Remove ICA Components (TESA)', ...
    'Run TESA ICA', ...
    'Remove ICA Components (TESA)', ...
    'Remove Baseline', ...
    'Remove Bad Epoch', ...
    'Save New Set'};
ov = repmat({struct()}, 1, numel(t.steps));
% Step 6 — cubic interpolation of removed TMS window (TESA paper recommends
%           cubic; default is linear which is less accurate for the artifact
%           boundary).
ov{6}.interpolation = 'cubic';
% Step 9 — epoch window: [-1, 1] s gives 1 s pre-stim baseline and captures
%           all standard TEP components (N15 through P180) plus the 500-1000 ms
%           post-stim window required by the background-restoration quality metric.
ov{9}.timelim = [-1, 1];
% Step 12 — average re-reference (empty string = average reference in EEGLAB)
ov{12}.ref = '[]';
t.overrides = ov;
templates(end+1) = t;

%% ---- Resting-State EEG --------------------------------------------------
% Continuous-data pipeline per the PREP pipeline (Bigdely-Shamlo 2015) and
% standard EEGLAB recommendations.  Key decisions:
%   - Data stays continuous throughout cleaning; ICA trained on the full
%     recording gives better component stability than on short epochs.
%   - Average re-reference applied before ICA so the unmixing matrix is
%     learned on the intended reference (EEGLAB FAQ).
%   - CleanLine removes line noise via multi-taper decomposition, preserving
%     spectral content better than a notch filter.
%   - Epoching is a downstream analysis step, not part of cleaning — it is
%     deliberately omitted here.
t = blankTemplate();
t.name = 'Resting-State EEG';
t.steps = { ...
    'Load Data', ...
    'Load Channel Location', ...
    'Frequency Filter', ...
    'Frequency Filter (CleanLine)', ...
    'Remove Bad Channels', ...
    'Interpolate Channels', ...
    'Re-Reference', ...
    'Run ICA', ...
    'Label ICA Components', ...
    'Flag ICA Components for Rejection', ...
    'Remove Flagged ICA Components', ...
    'Save New Set'};
ov = repmat({struct()}, 1, numel(t.steps));
ov{3}.locutoff = 0.5;   % HPF at 0.5 Hz (wider than default 1 Hz for resting-state)
ov{3}.hicutoff = 40;    % LPF at 40 Hz (removes high-freq noise before ICA)
ov{7}.ref      = '[]';  % average reference
t.overrides = ov;
templates(end+1) = t;

%% ---- Minimal (HPF + ICA + bad channel removal) --------------------------
% The smallest pipeline that meets basic publication quality standards.
% Includes average re-referencing and a single ICA pass for blink/muscle
% removal — both are required for credible EEG reporting.  No line noise
% removal, no bad-epoch rejection, and no epoching are included; add those
% steps manually if the recording requires them.
t = blankTemplate();
t.name = 'Minimal (HPF + ICA + bad channels)';
t.steps = { ...
    'Load Data', ...
    'Load Channel Location', ...
    'Frequency Filter', ...
    'Remove Bad Channels', ...
    'Interpolate Channels', ...
    'Re-Reference', ...
    'Run ICA', ...
    'Label ICA Components', ...
    'Flag ICA Components for Rejection', ...
    'Remove Flagged ICA Components', ...
    'Save New Set'};
ov = repmat({struct()}, 1, numel(t.steps));
ov{3}.locutoff = 0.5;   % HPF at 0.5 Hz
ov{6}.ref      = '[]';  % average reference
t.overrides = ov;
templates(end+1) = t;

end

%% ---- helpers ---------------------------------------------------------------

function t = blankTemplate()
t = struct('name', '', 'steps', {{}}, 'overrides', {{}});
end
