
% SPDX-License-Identifier: GPL-3.0-or-later
% Copyright (C) 2023-2026 Aref Pariz and Wesley Dunne.
% Part of nestapp; see the LICENSE file for full terms.
function bundleDir = collectSupportBundle(targetDir, spec)
% COLLECTSUPPORTBUNDLE  Gather an on-demand support bundle for a bug report.
%
%   Syntax
%     bundleDir = collectSupportBundle(targetDir)
%     bundleDir = collectSupportBundle(targetDir, spec)
%
%   Inputs
%     targetDir  char        - parent directory for the bundle (timestamped
%                              subfolder created inside). Empty -> tempdir.
%     spec       struct array- (optional) the current pipeline spec to describe.
%
%   Outputs
%     bundleDir  char - the folder written.
%
%   Unlike saveErrorBundle (written automatically on a failure), this is the
%   user-initiated "Collect Support Bundle" action: it captures the
%   environment (nestappDoctor) and, if given, the current pipeline
%   (describePipeline). Metadata only - no recordings are included. Attach
%   the folder to a GitHub issue (see .github/ISSUE_TEMPLATE/bug_report.yml).
%
%   Side effects   Creates a folder and writes Markdown files.
%   See also: nestappDoctor, describePipeline, saveErrorBundle

if nargin < 1 || isempty(targetDir); targetDir = tempdir; end
if nargin < 2; spec = []; end

stamp     = char(datetime('now', 'Format', 'yyyyMMdd_HHmmss'));
bundleDir = fullfile(targetDir, sprintf('nestapp_support_%s', stamp));
if ~exist(bundleDir, 'dir'); mkdir(bundleDir); end

writeText(fullfile(bundleDir, 'environment.md'), ...
    safeCall(@() nestappDoctor('Quiet', true)));
if ~isempty(spec)
    writeText(fullfile(bundleDir, 'pipeline.md'), ...
        safeCall(@() describePipeline(spec, 'Quiet', true)));
end

readme = strjoin({ ...
    '# nestapp support bundle', '', ...
    'Generated by Help > Collect Support Bundle. Contains environment', ...
    'diagnostics and (if a pipeline was loaded) its description. No EEG', ...
    'recordings are included. Attach this folder to your GitHub issue.', ''}, newline);
writeText(fullfile(bundleDir, 'README.md'), readme);
end

% ── helpers ───────────────────────────────────────────────────────────────────

function out = safeCall(fn)
try
    out = fn();
catch ME
    out = sprintf('(could not collect: %s)', ME.message);
end
end

function writeText(fpath, text)
fid = fopen(fpath, 'w');
if fid < 0; return; end
fwrite(fid, text);
fclose(fid);
end
