% SPDX-License-Identifier: GPL-3.0-or-later
% Copyright (C) 2023-2026 Aref Pariz and Wesley Dunne.
% Part of nestapp; see the LICENSE file for full terms.
function plots = plotRegistry()
% PLOTREGISTRY  Metadata for every plot the Explore workspace can draw.
%
%   plots = PLOTREGISTRY() returns a 1-by-N struct array. Each element:
%     .name      unique display name, and the key a saved session stores
%     .category  taxonomy heading ('Waveform', 'Topography', 'Quantification')
%     .info      one-paragraph description for the Info panel
%     .draw      name of the drawing function, as a char. Resolved with
%                str2func at draw time rather than stored as a handle, so the
%                registry stays plain data: it can be saved into a session
%                file, compared in a test, and checked for existence the way
%                stepAvailability checks a plugin function.
%     .mode      curve mode passed to groupCurves ('TEP'|'GMFP'|'LMFP'), or ''
%                for plots that do not reduce to a single ROI curve
%     .layout    how the plot wants its axes minted:
%                  'single'    one axes filling the canvas (the default)
%                  'per-group' one axes per group, side by side, plus a shared
%                              colour bar
%                  'panel'     the plot owns the whole canvas and mints its own
%                A CLOSED set of three, deliberately: the tab switches on this
%                rather than on the draw function's NAME, so adding a plot never
%                means adding a case to the tab. That is what makes the promise
%                below - "nothing in the tab needs to change" - actually true.
%     .requires  what must be true before this can render:
%                  .groups   'any' (>=1) | 1 | 2 | '2+'
%                  .windows  true when windows of interest are needed
%                  .chanlocs true when electrode positions are needed
%     .params    makeParam metadata, one per setting the plot accepts. Each
%                key is EXACTLY an option name of the draw function, so the
%                edited values are handed straight to it with no translation
%                table to keep in step.
%
%   This mirrors stepRegistry / stepTaxonomy / stepAvailability / availableSteps
%   deliberately. The app already solved "an extensible catalogue of named
%   things, grouped for a picker, each declaring what it needs and greyed out
%   with a reason when it cannot run" - for pipeline steps. Plot types are the
%   same problem, and a second, different mechanism for them would mean two
%   places to add a feature and two ways for the UI to explain itself.
%
%   It also absorbs the old Plot Type radio buttons: TEP, GMFP and LMFP are
%   entries here, not a separate selector, so there is one catalogue rather
%   than a radio group plus a view switcher that have to agree.
%
%   Parameter DEFAULTS are deliberately not stored here. The draw function
%   already declares them in its own fillDefaults call, and a second copy in
%   the registry would be a second thing to keep true. What is stored is a
%   placeholder NAMING the default - '(on)', '(-50 300)' - so the table reads
%   as "leave this alone and you get this" while the value itself stays in one
%   place. Only params the user actually sets are passed to the draw function.
%
%   To add a plot: append one block below, add it to plotTaxonomy, and write
%   the draw function. Nothing in the tab needs to change.
%
%   See also: plotTaxonomy, plotAvailability, availablePlots, groupCurves

persistent cached
if ~isempty(cached)
    plots = cached;
    return
end

plots = struct('name', {}, 'category', {}, 'info', {}, 'draw', {}, ...
               'mode', {}, 'layout', {}, 'requires', {}, 'params', {});

%% ---- Waveform --------------------------------------------------------
p = blankPlot();
p.name     = 'TEP (ROI mean)';
p.category = 'Waveform';
p.mode     = 'TEP';
p.draw     = 'drawTEPOverlay';
p.info     = ['The signed TEP waveform: the mean across the ROI electrodes ' ...
              'of the trial-averaged data, one curve per group with a ' ...
              'confidence band. The default view, and the one the windows of ' ...
              'interest are measured on.'];
p.params   = waveformParams();
plots(end+1) = p;

p = blankPlot();
p.name     = 'GMFP (all channels)';
p.category = 'Waveform';
p.mode     = 'GMFP';
p.draw     = 'drawTEPOverlay';
p.info     = ['Global mean field power: the standard deviation across ALL ' ...
              'electrodes at each timepoint, computed on the trial average. ' ...
              'Identical to TESA''s GMFA. Being a spread rather than a ' ...
              'signed mean, it is always positive and ignores the ROI.'];
p.params   = waveformParams();
plots(end+1) = p;

p = blankPlot();
p.name     = 'LMFP (ROI only)';
p.category = 'Waveform';
p.mode     = 'LMFP';
p.draw     = 'drawTEPOverlay';
p.info     = ['Local mean field power: GMFP restricted to the ROI ' ...
              'electrodes. Useful when a global measure is dominated by ' ...
              'activity far from the coil.'];
p.params   = waveformParams();
plots(end+1) = p;

p = blankPlot();
p.name     = 'Difference wave';
p.category = 'Waveform';
p.mode     = 'TEP';
p.draw     = 'drawDifferenceWave';
p.requires.groups = 2;
p.info     = ['The second group minus the first, with a confidence interval ' ...
              'on the difference itself. Needs exactly two groups, because a ' ...
              'difference is only defined between a pair. In a paired design ' ...
              'this is the contrast the statistics are actually about.'];
% No confidence-band switch: the interval IS the plot here, and a difference
% wave without one invites reading noise as an effect.
p.params   = [ ...
    makeParam('direction', 'Contrast', '', 'second - first | first - second', ...
       ['Which way round to subtract. Left unset the second group added is ' ...
        'the one measured against the first, which makes the sign of every ' ...
        'deflection a consequence of the order the groups happened to be ' ...
        'loaded in. The two pictures carry the same result; pick the one ' ...
        'whose sign matches the question being asked.'], ...
       'type', 'string', 'placeholder', '(second - first)'), ...
    timeRangeParam(), shadeWindowsParam('off')];
plots(end+1) = p;

%% ---- Topography ------------------------------------------------------
p = blankPlot();
p.name     = 'Scalp map';
p.category = 'Topography';
p.mode     = 'TEP';
p.draw     = 'drawGroupTopo';
p.layout   = 'per-group';
p.requires.chanlocs = true;
p.info     = ['The scalp distribution averaged over a time window, one map ' ...
              'per group on a shared symmetric microvolt scale so the groups ' ...
              'can be compared by eye.'];
p.params   = [ ...
    makeParam('window', 'Time window', 'ms', 't1 t2', ...
       ['The interval to average over. Left unset it follows the FIRST window ' ...
        'of interest, so the map keeps describing the same interval as the ' ...
        'measures table when that window is edited.'], ...
       'type', 'vector', 'placeholder', '(first window of interest)'), ...
    scaleParams(), markerParams()];
plots(end+1) = p;

p = blankPlot();
p.name     = 'TEP-topo';
p.category = 'Topography';
p.mode     = 'TEP';
p.draw     = 'drawTEPTopo';
p.layout   = 'panel';
p.requires.chanlocs = true;
p.requires.windows  = true;
p.info     = ['The waveforms with a grid of scalp maps above them: one column ' ...
              'per window of interest, one row per group, on one shared ' ...
              'microvolt scale. Each map averages over its window rather than ' ...
              'sampling a latency, so a map and the measure beside it describe ' ...
              'the same interval - move a window and both follow.'];
p.params   = [ ...
    makeParam('mapWindows', 'Windows to map', '', '', ...
       ['Which windows get a column of maps. All of them unless a subset is ' ...
        'picked - which is what crowds a single-column figure, where six ' ...
        'columns leave each head too small to read and the titles ' ...
        'overlapping. Columns stay in the order the windows are DEFINED, so ' ...
        'they read left to right in time whatever order they were picked in.'], ...
       'type', 'stringlist', 'widget', 'multiselect', ...
       'choicesFrom', 'windows', 'placeholder', '(all of them)'), ...
    makeParam('mapScale', 'Colour scale', '', 'shared | per window', ...
       ['"shared" is one scale across the whole grid, so a group or a window ' ...
        'with twice the amplitude looks it. "per window" scales each column ' ...
        'on its own, which keeps the GROUPS comparable within a window - the ' ...
        'comparison the rows are for - while letting a late component read ' ...
        'at all, instead of sitting neutral against a scale an early peak ' ...
        'set. Each column then states its own limit in its title, and the ' ...
        'shared bar is dropped because there is no longer one to draw.'], ...
       'type', 'string', 'placeholder', '(shared)'), ...
    makeParam('curve', 'Curve panel', '', 'on|off', ...
       ['The waveforms under the grid. Turning them off gives the maps the ' ...
        'full height, for a figure whose point is the topography and whose ' ...
        'waveform is shown elsewhere.'], ...
       'type', 'logical', 'placeholder', '(on)'), ...
    timeRangeParam(), shadeWindowsParam('on')];
plots(end+1) = p;

%% ---- Quantification --------------------------------------------------
p = blankPlot();
p.name     = 'Window bars';
p.category = 'Quantification';
p.mode     = 'TEP';
p.draw     = 'drawWindowBars';
p.layout   = 'panel';
p.requires.windows = true;
p.info     = ['One panel per window of interest, a bar per group carrying the ' ...
              'group mean of the per-subject window measure, with a confidence ' ...
              'interval on it. Each subject is measured on their OWN curve and ' ...
              'the means are taken across subjects - for a peak that matters, ' ...
              'since a peak read off an average is flattened by latency jitter.'];
p.params   = makeParam('measure', 'Measure', '', 'mean | peak | area', ...
    ['Which per-window number to plot. "mean" is the average amplitude over ' ...
     'the window; "peak" the largest deflection of the window''s polarity, ' ...
     'meaningful for a signed TEP; "area" the integral, the natural one for ' ...
     'GMFP and LMFP.'], ...
    'type', 'string', 'placeholder', '(mean)');
plots(end+1) = p;

cached = plots;
end

% ── helpers ─────────────────────────────────────────────────────────────────

function p = blankPlot()
% An entry with the permissive defaults: available for any number of groups,
% needing neither windows nor electrode positions, and no settings of its own.
% Each block above then states only what makes it special, so a new entry
% cannot silently inherit a requirement it does not have.
p = struct('name', '', 'category', '', 'info', '', 'draw', '', 'mode', '', ...
           'layout', 'single', ...
           'requires', struct('groups', 'any', 'windows', false, 'chanlocs', false), ...
           'params', emptyParams());
end

function p = emptyParams()
% A 0x0 array of the makeParam shape - NOT struct([]), which has no fields and
% would make numel/fieldnames behave differently for a plot with no settings
% than for one whose settings were all removed.
p = makeParam('', '', '', '', '');
p(:) = [];
end

function p = waveformParams()
% The settings every group-overlay waveform accepts. Shared rather than
% repeated so TEP, GMFP and LMFP cannot drift apart in what they offer.
p = [timeRangeParam(), ...
     makeParam('showBand', 'Confidence band', '', 'on|off', ...
        ['Shade each group''s confidence interval. Turning it off leaves ' ...
         'the mean lines alone, which is a cleaner picture and a less ' ...
         'honest one - the band is what says how well the mean is pinned.'], ...
        'type', 'logical', 'placeholder', '(on)'), ...
     makeParam('legend', 'Legend', '', 'on|off', ...
        'Name each group and its subject count on the plot.', ...
        'type', 'logical', 'placeholder', '(on)'), ...
     makeParam('showTraces', 'Individual recordings', '', 'on|off', ...
        ['Draw every contributing recording as a thin line behind the group ' ...
         'means. This is how an outlying file is spotted: the group mean ' ...
         'cannot show one, and opening the file on its own removes the ' ...
         'context that made it look odd. Lines are files, not subjects - ' ...
         'the point is to see what averaging within a subject hid.'], ...
        'type', 'logical', 'placeholder', '(off)'), ...
     shadeWindowsParam('off')];
end

function p = timeRangeParam()
p = makeParam('xlim', 'Time range', 'ms', 't1 t2', ...
    ['Time axis limits. The default starts before the pulse so the ' ...
     'pre-stimulus baseline is visible, which is where a reader judges ' ...
     'whether the post-stimulus deflections mean anything.'], ...
    'type', 'vector', 'placeholder', '(-50 300)');
end

function p = scaleParams()
% Where the colour limits come from. Shared is the default and stays so: it is
% the only setting under which two maps side by side can be compared by eye,
% which is the whole reason they are side by side.
p = [ ...
    makeParam('scale', 'Colour scale', '', 'shared | per map', ...
       ['"shared" derives one symmetric scale across every map, so a group ' ...
        'with twice the amplitude looks it. "per map" gives each its own, ' ...
        'which is what to use when one large group flattens the others to ' ...
        'near-neutral and their TOPOGRAPHY - a separate question from their ' ...
        'amplitude - is what is being read. Each map then carries its own ' ...
        'bar, because there is no longer a shared scale to label.'], ...
       'type', 'string', 'placeholder', '(shared)'), ...
    makeParam('climit', 'Fixed limit', 'uV', '', ...
       ['Pin the scale to plus and minus this many microvolts, instead of ' ...
        'deriving it from the data. This is how two figures from different ' ...
        'runs become comparable - a derived scale changes with the data, so ' ...
        'the same colour means a different voltage in each. Setting it ' ...
        'overrides the choice above. One number, not a pair: zero has to ' ...
        'stay at the middle of the colour map or the neutral colour lands ' ...
        'somewhere other than no-deflection and the polarity misreads.'], ...
       'type', 'scalar', 'placeholder', '(derived from the data)')];
end

function p = markerParams()
p = [ ...
    makeParam('markers', 'Electrodes', '', 'off | dots | labels', ...
       ['Whether the electrode positions are drawn over the field, and ' ...
        'named. Off by default because sixty-odd dots obscure the field ' ...
        'they sit on; "labels" is for the one large map that has to show ' ...
        'WHICH channels a focus sits on, and is unreadable at grid size.'], ...
       'type', 'string', 'placeholder', '(off)'), ...
    makeParam('contours', 'Contour lines', '', '0-12', ...
       ['Iso-voltage contours over the interpolated field. 0 leaves the ' ...
        'colour alone, which reads more cleanly at small sizes; more lines ' ...
        'make the gradient legible in print and in greyscale.'], ...
       'type', 'integer', 'placeholder', '(5)')];
end

function p = shadeWindowsParam(dflt)
p = makeParam('showBands', 'Shade windows', '', 'on|off', ...
    ['Mark the windows of interest on the time axis, so each measured ' ...
     'interval can be seen against the waveform it was measured on.'], ...
    'type', 'logical', 'placeholder', ['(' dflt ')']);
end
