function steps = stepRegistry()
% STEPREGISTRY  Returns metadata for all nestapp pipeline steps.
%
%   steps = stepRegistry() returns a 1-by-N struct array. Each element:
%     .name      - exact string matching the switch case in runPipelineCore.m
%                  and the StepsListBox item in nestapp.m
%     .defaults  - struct of default parameter values
%     .info      - description shown in the Info panel
%     .params    - struct array of per-field metadata:
%                    .key          raw field name (must match dispatchStep switch/case)
%                    .friendlyName display label shown in UITable
%                    .unit         unit string ('Hz', 'ms', 's', 'uV', '' ...)
%                    .validRange   string describing valid input ('on|off', '[0 Inf]', ...)
%                    .description  one-line tooltip
%                    .type         'scalar'|'integer'|'vector'|'logical'|'string'|'stringlist'
%
%   To add a step: append one block below, then add the matching case
%   in runPipelineCore.m.
%
% Copyright (C) 2023  Aref Pariz, University of Ottawa & The Royal
% Institute for Mental Health, Ottawa, Ontario, Canada.

% Persistent cache: stepRegistry() is called from startupFcn, LoadPipeline,
% and LoadTemplate — avoid rebuilding the full struct array on every call.
persistent cachedSteps
if ~isempty(cachedSteps)
    steps = cachedSteps;
    return
end

steps = struct('name',{},'defaults',{},'info',{},'params',{},'requires',{});

%% ---- Load Data -------------------------------------------------------
s = blankStep();
s.name = 'Load Data';
s.defaults.redraw = 'on';
s.info = ['EEGLAB: Uses "pop_loadX" where X is the data format ' ...
    '(set, cnt, vhdr, cdt). Loads the file selected in ' ...
    '"Select Data to Perform Analysis". ' ...
    'Supported formats: .set (EEGLAB), .vhdr (BrainVision), ' ...
    '.cnt (Neuroscan), .cdt (Curry).'];
s.params = makeParam('redraw','Redraw EEGLAB','','on|off', ...
    'Update the EEGLAB GUI window after loading.', 'type', 'logical');
s.requires = [ ...
    req('pop_loadbv',  'bva-io',  'EEGLAB Plugin Manager → search "bva-io"',   '.vhdr'), ...
    req('pop_loadcnt', 'loadcnt', 'EEGLAB Plugin Manager → search "loadcnt"',  '.cnt'), ...
    req('loadcurry',   'curry',   'EEGLAB Plugin Manager → search "curry"',    '.cdt')];
steps(end+1) = s;

%% ---- Load Channel Location -------------------------------------------
s = blankStep();
s.name = 'Load Channel Location';
s.defaults.needchanloc    = 'no';
s.defaults.eachFilediffPath = 'no';
s.info = ['A file picker will open to select a channel location file. ' ...
    'EEGLAB: "pop_chanedit" automatically detects locations using ' ...
    'the selected file and the standard_1005 electrode profile ' ...
    'from the EEGLAB dipfit plugin. ' ...
    'Set "Load location" to yes if your data lacks channel coordinates.'];
s.params = [ ...
    makeParam('needchanloc',    'Load location',           '', 'yes|no', ...
       'Open file picker to select a channel location file.', 'type', 'logical'), ...
    makeParam('eachFilediffPath','Different path per file','', 'yes|no', ...
       'Ask for a new location file for each data file in the batch.', 'type', 'logical')];
steps(end+1) = s;

%% ---- Save New Set ----------------------------------------------------
s = blankStep();
s.name = 'Save New Set';
s.defaults.setname         = 'New Set';
s.defaults.comments        = '[]';
s.defaults.overwrite       = 'off';
s.defaults.saveold         = '[]';
s.defaults.savenew         = '[]';
s.defaults.retrieve        = NaN;
s.defaults.gui             = 'off';
s.defaults.includeFileName = 'yes';
s.info = ['EEGLAB: Uses "pop_newset" to save current EEG as a new dataset. ' ...
    'Updates EEG and ALLEEG. The output filename is built from the ' ...
    'input filename plus the suffix in "Save as" (savenew). ' ...
    'Leave "Save old as" (saveold) empty to discard the pre-step data.'];
s.params = [ ...
    makeParam('setname',        'Dataset label',   '', '',         'Label stored in EEG.setname.', 'type', 'string'), ...
    makeParam('overwrite',      'Overwrite',       '', 'on|off',   'Overwrite existing file without prompting.', 'type', 'logical'), ...
    makeParam('saveold',        'Save old as',     '', '',         'Suffix for saving the pre-step dataset. Leave [] to skip.', 'type', 'string'), ...
    makeParam('savenew',        'Save as (suffix)','', '',         'Suffix appended to the input filename for the output .set file.', 'type', 'string'), ...
    makeParam('includeFileName','Prefix with filename','','yes|no','Prepend the input filename to the saved file path.', 'type', 'logical')];
steps(end+1) = s;

%% ---- Choose Data Set -------------------------------------------------
s = blankStep();
s.name = 'Choose Data Set';
s.defaults.dataSetInd = '';
s.info = ['EEGLAB: Retrieves a previously stored dataset from ALLEEG by index. ' ...
    'Useful when you need to branch back to an earlier processing stage ' ...
    'without reloading from disk. ' ...
    'EEGLAB function: pop_newset(..., ''retrieve'', index).'];
s.params = makeParam('dataSetInd','Dataset index','','integer >= 1', ...
    'Index of the dataset in ALLEEG to switch to.', 'type', 'integer');
steps(end+1) = s;

%% ---- Remove un-needed Channels ---------------------------------------
s = blankStep();
s.name = 'Remove un-needed Channels';
s.defaults.time      = [];
s.defaults.rmtime    = [];
s.defaults.point     = [];
s.defaults.rmpoint   = [];
s.defaults.trial     = [];
s.defaults.rmtrial   = [];
s.defaults.sorttrial = 'on';
s.defaults.nochannel = {'TP9','TP10'};
s.defaults.channel   = [];
s.defaults.chantype  = [];
s.defaults.rmchantype= [];
s.info = ['EEGLAB: Uses "pop_select" to remove specified channels. ' ...
    'By default removes TP9 and TP10 (ear reference electrodes). ' ...
    'Edit "Remove channels" to list any electrodes you want excluded. ' ...
    'Channel names are case-insensitive.'];
s.params = [ ...
    makeParam('nochannel','Remove channels','','cell of labels', ...
       'List of electrode labels to remove, e.g. {''TP9'',''TP10''}.', 'type', 'stringlist'), ...
    makeParam('channel',  'Keep channels', '','cell of labels or []', ...
       'If set, keep only these channels (alternative to nochannel).', 'placeholder', '(keep all)', 'type', 'stringlist')];
steps(end+1) = s;

%% ---- Remove Baseline -------------------------------------------------
s = blankStep();
s.name = 'Remove Baseline';
s.defaults.timerange  = [];
s.defaults.pointrange = [];
s.defaults.chanlist   = [];
s.info = ['EEGLAB: Uses "pop_rmbase" to subtract the mean amplitude ' ...
    'of a baseline window from each trial. ' ...
    'Leave "Time range" as [] to use the entire pre-stimulus period. ' ...
    'Specify [tmin tmax] in ms to define a custom baseline window. ' ...
    'Recommended: run after epoching so a pre-stimulus period exists.'];
s.params = [ ...
    makeParam('timerange', 'Time range',  'ms','[tmin tmax] or []', ...
       'Baseline window in ms. [] uses all available pre-stimulus time.', 'placeholder', '(full pre-stimulus)', 'type', 'vector'), ...
    makeParam('pointrange','Point range', 'samples','[p1 p2] or []', ...
       'Baseline as sample indices (alternative to time range).', 'placeholder', '(use timerange instead)', 'type', 'vector'), ...
    makeParam('chanlist',  'Channels',    '','[] = all', ...
       'Restrict baseline removal to these channel indices.', 'placeholder', '(all channels)', 'type', 'vector')];
steps(end+1) = s;

%% ---- Remove Bad Channels ---------------------------------------------
s = blankStep();
s.name = 'Remove Bad Channels';
s.defaults.impelec   = {''};
s.defaults.elec      = [];
s.defaults.threshold = 5;
s.defaults.norm      = 'on';
s.defaults.measure   = 'kurt';
s.defaults.freqrange = [1 6];
s.info = ['EEGLAB: Uses "pop_rejchan" to detect and remove bad channels ' ...
    'based on a statistical measure (kurtosis, probability, or spectrum). ' ...
    'Channels whose measure exceeds ''Threshold'' SDs from the mean are removed. ' ...
    'Specify ''Protected electrodes'' to prevent important channels (e.g., Cz) ' ...
    'from being rejected regardless of their statistics.'];
s.params = [ ...
    makeParam('impelec',   'Protected electrodes','','cell of labels', ...
       'Electrodes that cannot be rejected (e.g., reference or TMS site).', 'type', 'stringlist'), ...
    makeParam('elec',      'Evaluate channels',   '','[] = all', ...
       'Channel indices to assess. [] uses all channels.', 'placeholder', '(all channels)', 'type', 'vector'), ...
    makeParam('threshold', 'Threshold',           'SD','[0 Inf]', ...
       'Channels exceeding this many SDs from the mean are rejected.'), ...
    makeParam('norm',      'Normalize',           '','on|off', ...
       'Normalize measure across channels before thresholding.', 'type', 'logical'), ...
    makeParam('measure',   'Measure',             '','kurt|prob|spec', ...
       'kurt = kurtosis, prob = probability, spec = spectral power.', 'type', 'string'), ...
    makeParam('freqrange', 'Frequency range',     'Hz','[flo fhi]', ...
       'Frequency band for spectral measure (ignored for kurt/prob).', 'type', 'vector')];
steps(end+1) = s;

%% ---- Clean Artifacts -------------------------------------------------
s = blankStep();
s.name = 'Clean Artifacts';
s.defaults.ChannelCriterion             = 0.8;
s.defaults.LineNoiseCriterion           = 4;
s.defaults.Channels_ignore              = [];
s.defaults.Channels                     = [];
s.defaults.BurstCriterion               = 5;
s.defaults.WindowCriterion              = 0.25;
s.defaults.Highpass                     = [0.25 0.75];
s.defaults.ChannelCriterionMaxBadTime   = 0.5;
s.defaults.BurstCriterionRefMaxBadChns  = 0.075;
s.defaults.BurstCriterionRefTolerances  = [-inf 5.5];
s.defaults.BurstRejection               = 'off';
s.defaults.WindowCriterionTolerances    = [-inf 7];
s.defaults.FlatlineCriterion            = 5;
s.defaults.NoLocsChannelCriterion       = 0.45;
s.defaults.NoLocsChannelCriterionExcluded = 0.1;
s.info = ['EEGLAB: Uses "clean_artifacts" (ASR) to remove flatline channels, ' ...
    'low-frequency drifts, noisy channels, short-time bursts, and ' ...
    'incompletely repaired segments. Operates on continuous data. ' ...
    'ChannelCriterion: minimum correlation with neighbouring channels (0–1). ' ...
    'BurstCriterion: ASR cutoff in SDs — lower = more aggressive cleaning. ' ...
    'WindowCriterion: fraction of bad channels per window before rejection (0–1).'];
s.params = [ ...
    makeParam('ChannelCriterion',   'Channel correlation','','[0 1]', ...
       'Min correlation with neighbours. Channels below this are removed.'), ...
    makeParam('LineNoiseCriterion', 'Line noise threshold','SD','[0 Inf]', ...
       'Channels exceeding this line-noise-to-signal ratio are removed.'), ...
    makeParam('BurstCriterion',     'Burst threshold',    'SD','[0 Inf]', ...
       'ASR standard deviation cutoff. Lower = more aggressive burst removal.'), ...
    makeParam('WindowCriterion',    'Window rejection',   '','[0 1]', ...
       'Fraction of bad channels in a window before the window is removed.'), ...
    makeParam('FlatlineCriterion',  'Flatline duration',    's','[0 Inf]', ...
       'Max seconds a channel can be flat before being removed.'), ...
    makeParam('Highpass',           'High-pass filter',    'Hz','[transition] or off', ...
       'Apply high-pass before cleaning (e.g. [0.25 0.75]). off = skip.', 'type', 'vector'), ...
    makeParam('Channels_ignore',           'Ignore channels',     '','[] or cell of labels', ...
       'Channels excluded from artifact detection (e.g. reference electrode).', 'placeholder', '(none ignored)', 'type', 'stringlist'), ...
    makeParam('Channels',                  'Evaluate channels',   '','[] = all', ...
       'Restrict detection to these channels. [] = all channels.', 'placeholder', '(all channels)', 'type', 'vector'), ...
    makeParam('BurstRejection',            'Remove bursts',       '','on|off', ...
       'on = remove burst windows. off = repair them using ASR reconstruction.', 'type', 'logical'), ...
    makeParam('ChannelCriterionMaxBadTime','Max bad time',         '%','[0 1]', ...
       'Maximum fraction of time a channel can be bad before removal.'), ...
    makeParam('WindowCriterionTolerances',      'Window tolerances',    'SD','[-Inf Inf]', ...
       'Acceptable SD range for window rejection ([low high], e.g. [-Inf 7]).', 'type', 'vector'), ...
    makeParam('BurstCriterionRefMaxBadChns',   'ASR ref max bad chns', '%','[0 1]', ...
       'Max fraction of bad channels allowed in ASR calibration data.'), ...
    makeParam('BurstCriterionRefTolerances',   'ASR ref tolerances',   'SD','[-Inf Inf]', ...
       'SD range for selecting ASR calibration windows ([low high]).', 'type', 'vector'), ...
    makeParam('NoLocsChannelCriterion',        'No-locs threshold',    '','[0 1]', ...
       'Correlation threshold for channels without location data.'), ...
    makeParam('NoLocsChannelCriterionExcluded','No-locs excl. fraction','','[0 1]', ...
       'Fraction of neighbours excluded when computing no-locs correlation.')];
s.requires = req('clean_artifacts', 'clean_rawdata', ...
    'EEGLAB Plugin Manager → search "clean_rawdata" (bundled with most EEGLAB versions)');
steps(end+1) = s;

%% ---- Automatic Continuous Rejection ----------------------------------
s = blankStep();
s.name = 'Automatic Continuous Rejection';
s.defaults.elecrange            = 1:64;
s.defaults.epochlength          = 0.5;
s.defaults.overlap              = 0.25;
s.defaults.freqlimit            = [35 128];
s.defaults.mode                 = 'max';
s.defaults.correct              = 'remove';
s.defaults.threshold            = 10;
s.defaults.contiguous           = 4;
s.defaults.addlength            = 0.25;
s.defaults.eegplot              = 'off';
s.defaults.onlyreturnselection  = 'off';
s.defaults.verbose              = 'off';
s.defaults.taper                = 'hamming';
s.info = ['EEGLAB: Uses "pop_rejcont" to reject continuous portions of data ' ...
    'based on spectral thresholding. Slides a window over the continuous ' ...
    'recording and rejects segments where spectral power in the frequency ' ...
    'band exceeds the threshold. Input must be continuous (not epoched). ' ...
    'Useful for removing gross movement or electrical artifacts.'];
s.params = [ ...
    makeParam('elecrange',   'Channel range',    '','[first last]', ...
       'Indices of channels to evaluate.', 'type', 'vector'), ...
    makeParam('epochlength', 'Window length',    's','[0 Inf]', ...
       'Length of the sliding analysis window.'), ...
    makeParam('overlap',     'Window overlap',   's','[0 epoch length]', ...
       'Overlap between consecutive windows.'), ...
    makeParam('freqlimit',   'Frequency band',   'Hz','[flo fhi]', ...
       'Frequency range for spectral thresholding.', 'type', 'vector'), ...
    makeParam('threshold',   'Threshold',        'dB','[0 Inf]', ...
       'Spectral power threshold above baseline for rejection.'), ...
    makeParam('mode',    'Detection mode',   '', 'max|sum', ...
       'max = flag if any channel exceeds threshold. sum = use channel sum.', 'type', 'string'), ...
    makeParam('correct', 'Correction',       '', 'remove|fill', ...
       'remove = delete flagged segments. fill = replace with interpolated data.', 'type', 'string'), ...
    makeParam('taper',      'Spectral window', '', 'hamming|hann|blackman|none', ...
       'Window function applied before spectral estimation.', 'type', 'string'), ...
    makeParam('contiguous', 'Contiguous windows','','integer >= 1', ...
       'Minimum number of contiguous bad windows before a segment is rejected.', 'type', 'integer'), ...
    makeParam('addlength',  'Padding',         's','[0 Inf]', ...
       'Extra seconds added before/after each rejected segment.')];
steps(end+1) = s;

%% ---- Automatic Cleaning Data -----------------------------------------
s = blankStep();
s.name = 'Automatic Cleaning Data';
s.defaults.FlatlineCriterion        = 5;
s.defaults.ChannelCriterion         = 0.8;
s.defaults.LineNoiseCriterion       = 4;
s.defaults.Highpass                 = 'off';
s.defaults.BurstCriterion           = 20;
s.defaults.WindowCriterion          = 0.25;
s.defaults.BurstRejection           = 'on';
s.defaults.Distance                 = 'Euclidian';
s.defaults.channels_ignore          = {''};
s.defaults.WindowCriterionTolerances= [-Inf 7];
s.info = ['EEGLAB: Uses "pop_clean_rawdata" to automatically clean continuous ' ...
    'EEG data. Removes flat channels, noisy channels, and burst artifacts. ' ...
    'Input must be continuous (not epoched). ' ...
    'FlatlineCriterion: max flat duration in seconds before channel removal. ' ...
    'ChannelCriterion: min correlation with neighbours (0–1). ' ...
    'BurstCriterion: ASR SD cutoff — 20 is conservative, 5 is aggressive.'];
s.params = [ ...
    makeParam('FlatlineCriterion',  'Flatline duration', 's','[0 Inf]', ...
       'Max flat seconds before a channel is removed.'), ...
    makeParam('ChannelCriterion',   'Channel correlation','','[0 1]', ...
       'Min correlation with neighbours. Channels below this are removed.'), ...
    makeParam('BurstCriterion',     'Burst threshold',   'SD','[0 Inf]', ...
       'ASR cutoff. Typical range 5–20. Lower = more aggressive.'), ...
    makeParam('WindowCriterion',    'Window rejection',  '','[0 1] or off', ...
       'Fraction of bad channels per window to trigger window rejection.'), ...
    makeParam('Highpass',           'High-pass',         'Hz','[transition] or off', ...
       'Apply high-pass filter before cleaning. off = skip.', 'type', 'vector'), ...
    makeParam('LineNoiseCriterion', 'Line noise threshold','SD','[0 Inf]', ...
       'Channels exceeding this line-noise-to-signal ratio are removed.'), ...
    makeParam('BurstRejection',     'Remove bursts',     '','on|off', ...
       'on = remove burst windows. off = repair them using ASR reconstruction.', 'type', 'logical'), ...
    makeParam('channels_ignore',    'Ignore channels',   '','cell of labels or {}', ...
       'Channels excluded from artifact detection.', 'placeholder', '(none ignored)', 'type', 'stringlist'), ...
    makeParam('Distance',                  'Distance metric',   '','Euclidian|riemannian', ...
       'Distance metric for ASR. Euclidian = standard.', 'type', 'string'), ...
    makeParam('WindowCriterionTolerances', 'Window tolerances', 'SD','[-Inf Inf]', ...
       'Acceptable SD range for window rejection ([low high], e.g. [-Inf 7]).', 'type', 'vector')];
s.requires = req('pop_clean_rawdata', 'clean_rawdata', ...
    'EEGLAB Plugin Manager → search "clean_rawdata" (bundled with most EEGLAB versions)');
steps(end+1) = s;

%% ---- De-Trend Epoch --------------------------------------------------
s = blankStep();
s.name = 'De-Trend Epoch';
s.defaults.npoly = 1;
s.info = ['EEGLAB: Uses the built-in "detrend" function to remove polynomial ' ...
    'trends from each channel and epoch. ' ...
    'npoly = 1 removes a linear trend (default). ' ...
    'npoly = 2 removes a quadratic trend. ' ...
    'Run after epoching. Helps reduce slow drifts before ICA.'];
s.params = makeParam('npoly','Polynomial order','','1|2', ...
    '1 = linear detrend, 2 = quadratic detrend.', 'type', 'integer');
steps(end+1) = s;

%% ---- TESA De-Trend ---------------------------------------------------
s = blankStep();
s.name = 'TESA De-Trend';
s.defaults.detrend = 'linear';
s.defaults.timeWin = [11, 500];
s.info = ['TESA: Uses "pop_tesa_detrend" to remove a fitted trend from each channel. ' ...
    'A linear or polynomial function is fitted to the data within the time window ' ...
    'and subtracted. Run after epoching and TMS artifact removal. ' ...
    'Time window should exclude the TMS artifact (typically start at 10–15 ms).'];
s.params = [ ...
    makeParam('detrend','Detrend type','','linear|polynomial', ...
       'Type of function to fit and subtract.', 'type', 'string'), ...
    makeParam('timeWin','Time window','ms','[tstart tend]', ...
       'Window for fitting the trend. Start after TMS artifact (e.g. [11 500]).', 'type', 'vector')];
s.requires = req('pop_tesa_detrend', 'TESA', ...
    'EEGLAB Plugin Manager → search "TESA" (v1.1.1 or later)');
steps(end+1) = s;

%% ---- Re-Sample -------------------------------------------------------
s = blankStep();
s.name = 'Re-Sample';
s.defaults.freq = 1000;
s.defaults.fc   = 0.9;
s.defaults.df   = 0.2;
s.info = ['EEGLAB: Uses "pop_resample" to change the sampling rate. ' ...
    'An anti-aliasing low-pass filter is applied before downsampling. ' ...
    'Typical target rates: 1000 Hz (standard), 500 Hz (memory-constrained). ' ...
    'fc and df control the anti-aliasing filter shape (advanced — defaults are safe). ' ...
    'fc: normalised transition band centre (0–1, relative to Nyquist). ' ...
    'df: normalised transition band width (0–1). Smaller = sharper filter, more ringing.'];
s.params = [ ...
    makeParam('freq','Resample rate',           'Hz',  '[1 Inf]', ...
       'Target sampling frequency after resampling.'), ...
    makeParam('fc',  'Filter transition centre','norm','[0 1]', ...
       'Anti-aliasing filter centre, normalised to Nyquist (0.9 = safe default).'), ...
    makeParam('df',  'Filter transition width', 'norm','[0 1]', ...
       'Anti-aliasing filter transition width, normalised to Nyquist (0.2 = safe default).')];
steps(end+1) = s;

%% ---- Re-Reference ----------------------------------------------------
s = blankStep();
s.name = 'Re-Reference';
s.defaults.ref        = 'Cz';
s.defaults.exclude    = [];
s.defaults.interpchan = 'off';
s.defaults.keepref    = 'off';
s.defaults.refloc     = [];
s.info = ['EEGLAB: Uses "pop_reref" to re-reference the data to a new electrode or montage. ' ...
    'Common choices: a single electrode label (e.g. ''Cz''), ''[]'' for average reference, ' ...
    'or a list of labels for linked mastoids. ' ...
    'Run this step after ICA to avoid distorting the decomposition. ' ...
    'keepref = on retains the original reference channel in the data.'];
s.params = [ ...
    makeParam('ref',       'Reference',         '','label or []', ...
       'Reference electrode label (e.g. ''Cz'') or [] for average reference.', 'type', 'string'), ...
    makeParam('exclude',   'Exclude channels',  '','[] or indices', ...
       'Channels excluded from the average reference calculation.', 'placeholder', '(none excluded)', 'type', 'vector'), ...
    makeParam('interpchan','Interpolate ref',   '','on|off', ...
       'Interpolate the old reference channel back into the data.', 'type', 'logical'), ...
    makeParam('keepref',   'Keep reference',    '','on|off', ...
       'Retain the reference electrode as a flat channel after re-referencing.', 'type', 'logical'), ...
    makeParam('refloc',   'Reference location','','struct or []', ...
       'Channel location struct for the reference if not already in the montage.', 'placeholder', '(auto)', 'type', 'string')];
steps(end+1) = s;

%% ---- Frequency Filter (CleanLine) ------------------------------------
s = blankStep();
s.name = 'Frequency Filter (CleanLine)';
s.defaults.bandwidth     = 2;
s.defaults.chanlist      = [1 64];
s.defaults.computepower  = 1;
s.defaults.linefreqs     = [60 120];
s.defaults.newversion    = 0;
s.defaults.normSpectrum  = 0;
s.defaults.p             = 0.01;
s.defaults.pad           = 2;
s.defaults.plotfigures   = 0;
s.defaults.scanforlines  = 1;
s.defaults.sigtype       = 'Channels';
s.defaults.taperbandwidth= 2;
s.defaults.tau           = 100;
s.defaults.verb          = 1;
s.defaults.winsize       = 4;
s.defaults.winstep       = 1;
s.info = ['EEGLAB plugin: Uses "CleanLine" to adaptively remove line noise ' ...
    'at specified frequencies using sinusoidal regression in overlapping windows. ' ...
    'More effective than a notch filter for removing line noise without ' ...
    'distorting the surrounding spectrum. ' ...
    'linefreqs: frequencies to suppress (e.g. [60 120] for 60 Hz + harmonic). ' ...
    'p: significance threshold for line detection. ' ...
    'Requires the CleanLine plugin to be installed in EEGLAB.'];
s.params = [ ...
    makeParam('linefreqs',  'Line frequencies',   'Hz', '[f1 f2 ...]', ...
       'Frequencies to suppress (e.g. [60 120] for 60 Hz and its harmonic).', 'type', 'vector'), ...
    makeParam('chanlist',   'Channel range',      '',   '[first last]', ...
       'Range of channel indices to process.', 'type', 'vector'), ...
    makeParam('bandwidth',  'Bandwidth',          'Hz', '[0 Inf]', ...
       'Bandwidth around each line frequency to consider.'), ...
    makeParam('p',          'p-value threshold',  '',   '[0 1]', ...
       'Significance threshold for line detection. Smaller = more conservative.'), ...
    makeParam('winsize',    'Window size',        's',  '[0 Inf]', ...
       'Analysis window length in seconds.'), ...
    makeParam('winstep',      'Window step',        's',  '[0 winsize]', ...
       'Step between windows in seconds.'), ...
    makeParam('pad',          'FFT padding',        'x', '1|2|3|4', ...
       'Zero-padding factor for FFT (1 = none, 2 = 2×, etc.).', 'type', 'integer'), ...
    makeParam('taperbandwidth','Taper bandwidth',   'Hz', '[0 Inf]', ...
       'Bandwidth of the multi-taper used for spectral estimation.'), ...
    makeParam('tau',          'Convergence tau',    '',   '[0 Inf]', ...
       'Convergence parameter for the iterative line noise estimate.')];
s.requires = req('pop_cleanline', 'CleanLine', ...
    'EEGLAB Plugin Manager → search "CleanLine"');
steps(end+1) = s;

%% ---- Frequency Filter (TESA) -----------------------------------------
s = blankStep();
s.name = 'Frequency Filter (TESA)';
s.defaults.high = 1;
s.defaults.low  = 80;
s.defaults.ord  = 4;
s.defaults.type = 'bandpass';
s.info = ['TESA: Uses "pop_tesa_filtbutter" to apply a zero-phase Butterworth filter. ' ...
    'Types: bandpass, bandstop, highpass, lowpass. ' ...
    'Uses MATLAB butter + filtfilt (zero-phase — no temporal distortion). ' ...
    'For bandpass: high = lower cutoff, low = upper cutoff. ' ...
    'For highpass: set high only. For lowpass: set low only. ' ...
    'Recommendation: if performing both ERP and ICA, apply a 0.5 Hz high-pass ' ...
    'before ICA, then apply a 0.1 Hz high-pass to the unfiltered data for ERP. ' ...
    'Examples: bandpass 1–80 Hz (ord=4); bandstop 48–52 Hz (notch); highpass 1 Hz.'];
s.params = [ ...
    makeParam('high','High-pass cutoff','Hz','[0 Inf] or []', ...
       'Lower edge of passband (Hz). Leave [] for lowpass filter.'), ...
    makeParam('low', 'Low-pass cutoff', 'Hz','[0 Inf] or []', ...
       'Upper edge of passband (Hz). Leave [] for highpass filter.'), ...
    makeParam('ord', 'Filter order',    '',  'even integer >= 2', ...
       'Butterworth filter order. Higher = sharper roll-off, more ringing. 4 is standard.', 'type', 'integer'), ...
    makeParam('type','Filter type',     '',  'bandpass|bandstop|highpass|lowpass', ...
       'Type of filter to apply.', 'type', 'string')];
s.requires = req('pop_tesa_filtbutter', 'TESA', ...
    'EEGLAB Plugin Manager → search "TESA" (v1.1.1 or later)');
steps(end+1) = s;

%% ---- Frequency Filter ------------------------------------------------
s = blankStep();
s.name = 'Frequency Filter';
s.defaults.locutoff  = 1;
s.defaults.hicutoff  = 80;
s.defaults.filtorder = 0;
s.defaults.revfilt   = 0;
s.defaults.usefft    = 0;
s.defaults.plotfreqz = 0;
s.defaults.minphase  = 0;
s.defaults.usefftfilt= 0;
s.info = ['EEGLAB: Uses "pop_eegfiltnew" to apply a Hamming-windowed sinc FIR filter. ' ...
    'locutoff: lower passband edge (Hz) — set to 0 for lowpass. ' ...
    'hicutoff: upper passband edge (Hz) — set to 0 for highpass. ' ...
    'filtorder: filter length minus 1 — must be even. 0 = auto-calculate. ' ...
    'revfilt: 0 = bandpass, 1 = notch (band-stop). ' ...
    'minphase: use minimum-phase (causal) version instead of zero-phase.'];
s.params = [ ...
    makeParam('locutoff', 'High-pass cutoff', 'Hz','[0 Inf]', ...
       'Lower passband edge. 0 = no high-pass.'), ...
    makeParam('hicutoff', 'Low-pass cutoff',  'Hz','[0 Inf]', ...
       'Upper passband edge. 0 = no low-pass.'), ...
    makeParam('filtorder','Filter order',     '',  'even integer or 0', ...
       'FIR filter order. Must be even. 0 = auto-calculate from transition band.', 'type', 'integer'), ...
    makeParam('revfilt',  'Notch mode',          '',  '0|1', ...
       '0 = bandpass, 1 = invert to notch filter.', 'type', 'integer'), ...
    makeParam('usefft',   'Use FFT filter',      '',  '0|1', ...
       '1 = frequency-domain filtering via FFT. 0 = standard time-domain FIR.', 'type', 'integer'), ...
    makeParam('plotfreqz','Plot freq response',   '',  '0|1', ...
       '1 = display the frequency response of the designed filter.', 'type', 'integer'), ...
    makeParam('minphase',  'Minimum phase',       '',  '0|1', ...
       '1 = causal minimum-phase filter. 0 = zero-phase (default, no delay).', 'type', 'integer'), ...
    makeParam('usefftfilt','Use fftfilt',        '',  '0|1', ...
       '1 = use MATLAB fftfilt for filtering. 0 = use standard filter (default).', 'type', 'integer')];
s.requires = req('pop_eegfiltnew', 'firfilt', ...
    'EEGLAB Plugin Manager → search "firfilt" (bundled with most EEGLAB versions)');
steps(end+1) = s;

%% ---- Run ICA ---------------------------------------------------------
s = blankStep();
s.name = 'Run ICA';
s.defaults.icatype     = 'fastica';
s.defaults.approach    = 'symm';
s.defaults.g           = 'tanh';
s.defaults.stabilization = 'on';
s.info = ['EEGLAB: Uses "pop_runica" to decompose data into independent components. ' ...
    'icatype: algorithm — fastica (default, fast) or runica (slower, extended infomax). ' ...
    'approach: symm (parallel, default) or defl (sequential). ' ...
    'g: nonlinearity — tanh (for super-Gaussian sources), gauss, pow3, skew. ' ...
    'stabilization: on enables the stabilised FastICA variant (recommended). ' ...
    'Data should be high-pass filtered (>= 1 Hz) before ICA. ' ...
    'Requires FastICA to be on the MATLAB path.'];
s.params = [ ...
    makeParam('icatype',      'Algorithm',     '','fastica|runica', ...
       'ICA algorithm. fastica is faster; runica (extended infomax) is more stable.', 'type', 'string'), ...
    makeParam('approach',     'Approach',      '','symm|defl', ...
       'symm = all components in parallel. defl = one at a time (slower).', 'type', 'string'), ...
    makeParam('g',            'Nonlinearity',  '','tanh|gauss|pow3|skew', ...
       'tanh suits most EEG data. gauss is more robust to outliers.', 'type', 'string'), ...
    makeParam('stabilization','Stabilization', '','on|off', ...
       'Stabilised FastICA — recommended to improve convergence.', 'type', 'logical')];
steps(end+1) = s;

%% ---- Run TESA ICA ----------------------------------------------------
s = blankStep();
s.name = 'Run TESA ICA';
s.defaults.approach     = 'symm';
s.defaults.g            = 'gauss';
s.defaults.stabilization= 'on';
s.info = ['TESA: Uses "pop_tesa_fastica" to run FastICA on TMS-EEG data. ' ...
    'Equivalent to pop_runica with icatype=fastica but integrated into ' ...
    'the TESA pipeline for use with pop_tesa_compselect. ' ...
    'gauss nonlinearity is recommended for TMS-EEG (more robust to high-amplitude artifacts). ' ...
    'Requires FastICA to be on the MATLAB path. ' ...
    'Run after TMS artifact removal and before Remove ICA Components (TESA).'];
s.params = [ ...
    makeParam('approach',     'Approach',      '','symm|defl', ...
       'symm = all components simultaneously. defl = sequential.', 'type', 'string'), ...
    makeParam('g',            'Nonlinearity',  '','tanh|gauss|pow3|skew', ...
       'gauss is recommended for TMS-EEG data.', 'type', 'string'), ...
    makeParam('stabilization','Stabilization', '','on|off', ...
       'Stabilised FastICA — recommended.', 'type', 'logical')];
s.requires = [ ...
    req('pop_tesa_fastica', 'TESA',    'EEGLAB Plugin Manager → search "TESA" (v1.1.1 or later)'), ...
    req('fastica',          'FastICA', 'https://research.ics.aalto.fi/ica/fastica — download and add to MATLAB path')];
steps(end+1) = s;

%% ---- Label ICA Components --------------------------------------------
s = blankStep();
s.name = 'Label ICA Components';
s.defaults.version = 'default';
s.info = ['EEGLAB: Uses "pop_iclabel" to automatically classify ICA components ' ...
    'into categories: Brain, Muscle, Eye, Heart, Line Noise, Channel Noise, Other. ' ...
    'Returns a probability score for each category per component. ' ...
    'Must run after ICA decomposition. ' ...
    'version: ''default'' = full classifier; ''lite'' = faster, excludes autocorrelation; ' ...
    '''beta'' = older version (for reproducibility only).'];
s.params = makeParam('version','Classifier version','','default|lite|beta', ...
    'default = validated classifier. lite = faster. beta = legacy.', 'type', 'string');
s.requires = req('pop_iclabel', 'ICLabel', ...
    'EEGLAB Plugin Manager → search "ICLabel" (bundled with most EEGLAB versions)');
steps(end+1) = s;

%% ---- Flag ICA Components for Rejection -------------------------------
s = blankStep();
s.name = 'Flag ICA Components for Rejection';
s.defaults.Brain        = [NaN, NaN];
s.defaults.Muscle       = [0.9, 1];
s.defaults.Eye          = [0.9, 1];
s.defaults.Heart        = [NaN, NaN];
s.defaults.LineNoise    = [NaN, NaN];
s.defaults.ChannelNoise = [NaN, NaN];
s.defaults.Other        = [NaN, NaN];
s.info = ['EEGLAB: Uses "pop_icflag" to flag components for rejection based on ' ...
    'ICLabel probability thresholds. Each category takes a [min max] probability ' ...
    'range — components within that range are flagged. [NaN NaN] = do not flag. ' ...
    'Must run after Label ICA Components. ' ...
    'Example: Muscle = [0.9 1] flags components with >= 90% muscle probability. ' ...
    'Follow with Remove Flagged ICA Components to apply the rejection.'];
s.params = [ ...
    makeParam('Brain',       'Brain range',        '','[0 1] or [NaN NaN]', ...
       'Flag components with brain probability in this range. [NaN NaN] = skip.', 'type', 'vector'), ...
    makeParam('Muscle',      'Muscle range',       '','[0 1] or [NaN NaN]', ...
       'Flag components with muscle probability in this range.', 'type', 'vector'), ...
    makeParam('Eye',         'Eye range',          '','[0 1] or [NaN NaN]', ...
       'Flag components with eye probability in this range.', 'type', 'vector'), ...
    makeParam('Heart',       'Heart range',        '','[0 1] or [NaN NaN]', ...
       'Flag components with cardiac probability in this range.', 'type', 'vector'), ...
    makeParam('LineNoise',   'Line noise range',   '','[0 1] or [NaN NaN]', ...
       'Flag components with line noise probability in this range.', 'type', 'vector'), ...
    makeParam('ChannelNoise','Channel noise range','','[0 1] or [NaN NaN]', ...
       'Flag components with channel noise probability in this range.', 'type', 'vector'), ...
    makeParam('Other',       'Other range',        '','[0 1] or [NaN NaN]', ...
       'Flag components with ''other'' probability in this range.', 'type', 'vector')];
s.requires = req('pop_icflag', 'ICLabel', ...
    'EEGLAB Plugin Manager → search "ICLabel" (bundled with most EEGLAB versions)');
steps(end+1) = s;

%% ---- Remove Flagged ICA Components -----------------------------------
s = blankStep();
s.name = 'Remove Flagged ICA Components';
s.defaults.components = [];
s.defaults.plotag     = 0;
s.defaults.keepcomp   = 0;
s.info = ['EEGLAB: Uses "pop_subcomp" to subtract flagged ICA components from the data. ' ...
    'Removes components previously flagged by ''Flag ICA Components for Rejection''. ' ...
    'components: optionally specify additional component indices to remove manually. ' ...
    'keepcomp: set to 1 to keep rather than remove the specified components.'];
s.params = [ ...
    makeParam('components','Additional components','','[] or [c1 c2 ...]', ...
       'Extra component indices to remove in addition to flagged ones.', 'placeholder', '(flagged only)', 'type', 'vector'), ...
    makeParam('keepcomp',  'Keep mode',           '','0|1', ...
       '0 = remove listed, 1 = keep listed and remove all others.', 'type', 'integer'), ...
    makeParam('plotag',    'Plot activations',    '','0|1', ...
       '1 = plot component activations for inspection before removal.', 'type', 'integer')];
steps(end+1) = s;

%% ---- Remove ICA Components (TESA) ------------------------------------
s = blankStep();
s.name = 'Remove ICA Components (TESA)';
s.defaults.compCheck         = 'off';
s.defaults.tmsMuscle         = 'on';
s.defaults.tmsMuscleThresh   = 8;
s.defaults.tmsMuscleWin      = [11 30];
s.defaults.tmsMuscleFeedback = 'off';
s.defaults.blink             = 'off';
s.defaults.blinkThresh       = 2.5;
s.defaults.blinkElecs        = {'Fp1','Fp2'};
s.defaults.blinkFeedback     = 'off';
s.defaults.move              = 'off';
s.defaults.moveThresh        = 2;
s.defaults.moveElecs         = {'F7','F8'};
s.defaults.moveFeedback      = 'off';
s.defaults.muscle            = 'off';
s.defaults.muscleThresh      = 0.6;
s.defaults.muscleFreqIn      = [30 100];
s.defaults.muscleFeedback    = 'off';
s.defaults.muscleFreqEx      = [58 62];
s.defaults.elecNoise         = 'off';
s.defaults.elecNoiseThresh   = 4;
s.defaults.elecNoiseFeedback = 'off';
s.defaults.plotTimeX         = [-100 399];
s.defaults.plotFreqX         = [1 100];
s.info = ['TESA: Uses "pop_tesa_compselect" to automatically identify and remove ' ...
    'artifactual ICA components from the TESA FastICA decomposition. ' ...
    'TMS-evoked muscle: detects components with large amplitude in the 11–30 ms window. ' ...
    'Blink: detects components correlated with Fp1/Fp2. ' ...
    'Move: detects components correlated with F7/F8 (lateral eye movement). ' ...
    'Muscle: detects components with high-frequency spectral power (30–100 Hz). ' ...
    'Turn on each category and adjust thresholds as needed for your data.'];
s.params = [ ...
    makeParam('tmsMuscle',       'TMS muscle',           '',   'on|off', ...
       'Detect TMS-evoked muscle artifact components.', 'type', 'logical'), ...
    makeParam('tmsMuscleThresh', 'TMS muscle threshold', 'z',  '[0 Inf]', ...
       'Z-score threshold for TMS-evoked muscle detection.'), ...
    makeParam('tmsMuscleWin',    'TMS muscle window',    'ms', '[tstart tend]', ...
       'Time window for TMS muscle detection (e.g. [11 30]).', 'type', 'vector'), ...
    makeParam('blink',           'Eye blink',            '',   'on|off', ...
       'Detect blink artifact components (uses blinkElecs).', 'type', 'logical'), ...
    makeParam('blinkThresh',     'Blink threshold',      'z',  '[0 Inf]', ...
       'Z-score threshold for blink detection relative to other components.'), ...
    makeParam('blinkElecs',      'Blink electrodes',     '',   'cell of labels', ...
       'Electrodes used for blink detection (e.g. {''Fp1'',''Fp2''}).', 'type', 'stringlist'), ...
    makeParam('move',            'Eye movement',         '',   'on|off', ...
       'Detect lateral eye movement components (uses moveElecs).', 'type', 'logical'), ...
    makeParam('moveThresh',      'Movement threshold',   'z',  '[0 Inf]', ...
       'Z-score threshold for eye movement detection.'), ...
    makeParam('moveElecs',       'Movement electrodes',  '',   'cell of labels', ...
       'Electrodes for eye movement detection (e.g. {''F7'',''F8''}).', 'type', 'stringlist'), ...
    makeParam('muscle',          'Muscle (spectral)',     '',   'on|off', ...
       'Detect broadband muscle artifact based on spectral slope.', 'type', 'logical'), ...
    makeParam('muscleThresh',    'Muscle threshold',     '',   '[0 1]', ...
       'Spectral slope threshold for muscle detection.'), ...
    makeParam('muscleFreqIn',    'Muscle freq band',     'Hz', '[flo fhi]', ...
       'Frequency band for muscle spectral analysis.', 'type', 'vector'), ...
    makeParam('muscleFreqEx',    'Exclude band',         'Hz', '[flo fhi]', ...
       'Frequency band to exclude (e.g. line noise at [58 62]).', 'type', 'vector'), ...
    makeParam('elecNoise',       'Electrode noise',      '',   'on|off', ...
       'Detect electrode noise components.', 'type', 'logical'), ...
    makeParam('elecNoiseThresh', 'Electrode threshold',  'z',  '[0 Inf]', ...
       'Z-score threshold for electrode noise detection.'), ...
    makeParam('compCheck',  'Manual review',    '', 'on|off', ...
       'Open interactive GUI to review components before rejection.', 'type', 'logical'), ...
    makeParam('plotTimeX',  'Time plot range',  'ms','[tstart tend]', ...
       'Time axis range for component time-course plots.', 'type', 'vector'), ...
    makeParam('plotFreqX',  'Freq plot range',  'Hz','[flo fhi]', ...
       'Frequency axis range for component spectral plots.', 'type', 'vector')];
s.requires = req('pop_tesa_compselect', 'TESA', ...
    'EEGLAB Plugin Manager → search "TESA" (v1.1.1 or later)');
steps(end+1) = s;

%% ---- Epoching --------------------------------------------------------
s = blankStep();
s.name = 'Epoching';
s.defaults.types     = {'TMS'};
s.defaults.timelim   = [-2, 2];
s.defaults.epochinfo = 'yes';
s.info = ['EEGLAB: Uses "pop_epoch" to extract fixed-length epochs time-locked ' ...
    'to events. types: event label(s) to epoch around (e.g. {''TMS''}). ' ...
    'timelim: epoch window relative to event onset in seconds, e.g. [-1 1]. ' ...
    'Must run on continuous data. Run Find TMS Pulses before epoching to ' ...
    'ensure events are correctly labelled in EEG.event.'];
s.params = [ ...
    makeParam('types',    'Event label(s)', '',  'cell of strings', ...
       'Event type(s) to epoch around, e.g. {''TMS''}.', 'type', 'stringlist'), ...
    makeParam('timelim',  'Epoch window',   's', '[tstart tend]', ...
       'Epoch time limits relative to event onset in seconds (e.g. [-1 1]).', 'type', 'vector'), ...
    makeParam('epochinfo','Preserve info',  '',  'yes|no', ...
       'Retain event information in the epoched dataset.', 'type', 'logical')];
steps(end+1) = s;

%% ---- Remove Bad Epoch ------------------------------------------------
s = blankStep();
s.name = 'Remove Bad Epoch';
s.defaults.threshold = 1000;
s.defaults.electrodes= [];
s.defaults.icacomps  = [];
s.defaults.startprob = [];
s.defaults.maxrej    = [];
s.defaults.nogui     = 'on';
s.defaults.eegplot   = 'off';
s.info = ['EEGLAB: Uses "pop_autorej" to automatically reject epochs exceeding ' ...
    'an amplitude threshold or with abnormal probability. ' ...
    'threshold: peak-to-peak amplitude in µV above which an epoch is rejected. ' ...
    'A common starting value is 1000 µV for TMS-EEG; adjust based on your data. ' ...
    'startprob: probability threshold (SDs) for joint probability rejection. ' ...
    'maxrej: maximum fraction of epochs to reject per iteration.'];
s.params = [ ...
    makeParam('threshold', 'Amplitude threshold','uV',   '[0 Inf]', ...
       'Epochs with peak-to-peak amplitude above this value are rejected.'), ...
    makeParam('electrodes','Channels',          '',    '[] = all', ...
       'Channel indices to evaluate. [] uses all channels.', 'placeholder', '(all channels)', 'type', 'vector'), ...
    makeParam('startprob', 'Probability threshold','SD','[0 Inf] or []', ...
       'Std deviations for joint probability rejection. [] = skip.', 'placeholder', '(skip)', 'type', 'scalar'), ...
    makeParam('maxrej',    'Max rejection rate', '',    '[0 1] or []', ...
       'Maximum fraction of epochs to reject per pass. [] = no limit.', 'placeholder', '(no limit)', 'type', 'scalar'), ...
    makeParam('icacomps',  'ICA components',    '',    '[] or [c1 c2 ...]', ...
       'Run rejection on these ICA component activations instead of raw channels.', 'placeholder', '(use channels)', 'type', 'vector')];
steps(end+1) = s;

%% ---- Remove Bad Trials -----------------------------------------------
s = blankStep();
s.name = 'Remove Bad Trials';
s.defaults.localThresh  = 5;
s.defaults.globalThresh = 5;
s.info = ['EEGLAB: Combines automatic and manual trial rejection. ' ...
    'First runs "pop_jointprob" to flag epochs where the joint probability of ' ...
    'the signal across channels exceeds localThresh (per-channel) or globalThresh ' ...
    '(across all channels) standard deviations. ' ...
    'Then opens the "pop_rejmenu" rejection GUI so you can review and manually ' ...
    'add or remove flagged epochs before confirming. ' ...
    'Confirmed rejections are removed with "pop_rejepoch". ' ...
    'Requires epoched data. Run after Remove Bad Epoch or as an alternative to it.'];
s.params = [ ...
    makeParam('localThresh',  'Local threshold',  'SD', '[0 Inf]', ...
       'Per-channel joint probability threshold. Epochs exceeding this SD are flagged.'), ...
    makeParam('globalThresh', 'Global threshold', 'SD', '[0 Inf]', ...
       'Across-channel joint probability threshold.')];
steps(end+1) = s;

%% ---- Find TMS Pulses (TESA) ------------------------------------------
s = blankStep();
s.name = 'Find TMS Pulses (TESA)';
s.defaults.elec       = 'Cz';
s.defaults.refract    = 3;
s.defaults.rate       = 10000;
s.defaults.tmslabel   = 'TMS';
s.defaults.plots      = 'off';
s.defaults.paired     = 'no';
s.defaults.repetitive = 'no';
s.defaults.ISI        = [];
s.defaults.pairlabel  = {'pp'};
s.defaults.ITI        = [];
s.defaults.pulseNum   = [];
s.info = ['TESA: Uses "pop_tesa_findpulse" to detect TMS pulses by finding ' ...
    'large-amplitude deflections in a reference channel. ' ...
    'elec: channel to search for artifacts (usually the electrode closest to the coil). ' ...
    'refract: refractory period in ms — minimum time between detected pulses. ' ...
    'rate: detection threshold in µV/ms (rate of change). Increase if false positives occur. ' ...
    'For paired-pulse paradigms (LICI, SAI): set paired=yes and enter the ISI in ms. ' ...
    'For rTMS: set repetitive=yes and provide ITI (inter-train interval) and pulseNum.'];
s.params = [ ...
    makeParam('elec',      'Reference electrode','',   'label', ...
       'Electrode to detect TMS artifacts in (closest to coil site).', 'type', 'string'), ...
    makeParam('refract',   'Refractory period',  'ms', '[0 Inf]', ...
       'Minimum time between successive detected pulses.'), ...
    makeParam('rate',      'Detection rate',     'uV/ms','[0 Inf]', ...
       'Rate-of-change threshold. Increase to reduce false positives.'), ...
    makeParam('tmslabel',  'Event label',        '',   'string', ...
       'Label assigned to detected single TMS pulses in EEG.event.', 'type', 'string'), ...
    makeParam('paired',    'Paired-pulse',       '',   'yes|no', ...
       'Search for paired-pulse paradigms (LICI, SAI, etc.).', 'type', 'logical'), ...
    makeParam('ISI',       'ISI',                'ms', '[0 Inf] or []', ...
       'Inter-stimulus interval for paired-pulse detection.', 'placeholder', '(single pulse)', 'type', 'scalar'), ...
    makeParam('repetitive','Repetitive TMS',     '',   'yes|no', ...
       'Search for rTMS trains.', 'type', 'logical'), ...
    makeParam('ITI',       'Inter-train interval','ms','[0 Inf] or []', ...
       'Time between rTMS trains in ms.', 'placeholder', '(not applicable)', 'type', 'scalar'), ...
    makeParam('pairlabel','Pair event label',  '', 'cell of strings', ...
       'Event label for the conditioning pulse in paired-pulse paradigms.','{''pp''}','stringlist'), ...
    makeParam('pulseNum', 'Pulses per train',  '', '[0 Inf] or []', ...
       'Number of pulses per rTMS train.', 'placeholder', '(not applicable)', 'type', 'integer')];
s.requires = req('pop_tesa_findpulse', 'TESA', ...
    'EEGLAB Plugin Manager → search "TESA" (v1.1.1 or later)');
steps(end+1) = s;

%% ---- Remove TMS Artifacts (TESA) ------------------------------------
s = blankStep();
s.name = 'Remove TMS Artifacts (TESA)';
s.defaults.cutTimesTMS = [-2, 10];
s.defaults.replaceTimes= [];
s.defaults.cutEvent    = {'TMS'};
s.info = ['TESA: Uses "pop_tesa_removedata" to zero-out or replace the TMS artifact ' ...
    'window in each epoch. The artifact is replaced with 0s (or a baseline mean ' ...
    'if replaceTimes is set). Removed time points are stored in EEG.tmscut for ' ...
    'later interpolation. ' ...
    'cutTimesTMS: window to remove in ms relative to TMS pulse (e.g. [-2 10]). ' ...
    'replaceTimes: baseline window to replace the artifact with (e.g. [-500 -100]). ' ...
    'Can run on continuous or epoched data.'];
s.params = [ ...
    makeParam('cutTimesTMS', 'Remove window',  'ms','[tstart tend]', ...
       'Time window to zero-out around the TMS pulse (e.g. [-2 10]).', 'type', 'vector'), ...
    makeParam('replaceTimes','Replace with',   'ms','[tstart tend] or []', ...
       'Baseline window to use as replacement. [] replaces with zeros.', 'placeholder', '(replace with zeros)', 'type', 'vector'), ...
    makeParam('cutEvent',    'Event label(s)', '',  'cell of strings', ...
       'Event labels marking TMS pulses (e.g. {''TMS''}}).', 'type', 'stringlist')];
s.requires = req('pop_tesa_removedata', 'TESA', ...
    'EEGLAB Plugin Manager → search "TESA" (v1.1.1 or later)');
steps(end+1) = s;

%% ---- Fix TMS Pulse (TESA) -------------------------------------------
s = blankStep();
s.name = 'Fix TMS Pulse (TESA)';
s.defaults.elec      = 'Cz';
s.defaults.epoch_len = [-1, 1];
s.defaults.type      = 'TMS';
s.defaults.refract   = 4;
s.defaults.rate      = 1e4;
s.defaults.paired    = 'no';
s.defaults.ISI       = [];
s.info = ['TESA: Uses "tesa_fixevent" to correct TMS pulse latencies in already-epoched data. ' ...
    'For use when recorded event markers do not exactly coincide with the TMS pulse. ' ...
    'Detects the artifact by finding the largest rate-of-change in the reference channel ' ...
    'and realigns epochs to that time point. ' ...
    'Run before other TESA steps if pulse timing is inaccurate.'];
s.params = [ ...
    makeParam('elec',     'Reference electrode','',   'label', ...
       'Channel to detect the TMS artifact in.', 'type', 'string'), ...
    makeParam('epoch_len','Epoch window',       's',  '[tstart tend]', ...
       'Current epoch length in seconds (used to define search window).', 'type', 'vector'), ...
    makeParam('type',     'Event label',        '',   'string', ...
       'Event type label to search for and correct.', 'type', 'string'), ...
    makeParam('refract',  'Refractory period',  'ms', '[0 Inf]', ...
       'Minimum time between successive pulses.'), ...
    makeParam('rate',     'Detection rate',     'uV/ms','[0 Inf]', ...
       'Rate-of-change threshold for artifact detection.'), ...
    makeParam('paired',   'Paired-pulse',       '',    'yes|no', ...
       'Correct pulse timing for paired-pulse paradigms.', 'type', 'logical'), ...
    makeParam('ISI',      'ISI',                'ms',  '[0 Inf] or []', ...
       'Inter-stimulus interval for paired-pulse correction.', 'placeholder', '(single pulse)', 'type', 'scalar')];
s.requires = req('tesa_fixevent', 'TESA', ...
    'EEGLAB Plugin Manager → search "TESA" (v1.1.1 or later)');
steps(end+1) = s;

%% ---- Interpolate Channels -------------------------------------------
s = blankStep();
s.name = 'Interpolate Channels';
s.defaults.method = 'spherical';
s.defaults.trange = [];
s.info = ['EEGLAB: Uses "pop_interp" to interpolate previously removed channels. ' ...
    'Restores channels that were rejected (e.g. by Remove Bad Channels) using ' ...
    'spherical spline interpolation from neighbouring electrodes. ' ...
    'Run after channel rejection and before re-referencing. ' ...
    'Requires channel location information to be loaded.'];
s.params = [ ...
    makeParam('method','Interpolation method','','spherical|invdist|spacetime', ...
       'spherical = spline interpolation (recommended for EEG).', 'type', 'string'), ...
    makeParam('trange','Time range',         'ms','[tstart tend] or []', ...
       'Restrict interpolation to this time range. [] = entire epoch.', 'placeholder', '(full epoch)', 'type', 'vector')];
steps(end+1) = s;

%% ---- Interpolate Missing Data (TESA) ---------------------------------
s = blankStep();
s.name = 'Interpolate Missing Data (TESA)';
s.defaults.interpolation = 'linear';
s.defaults.interpWin     = [20, 20];
s.info = ['TESA: Uses "pop_tesa_interpdata" to replace the zeroed TMS artifact ' ...
    'window with interpolated data. ' ...
    'Must be run after Remove TMS Artifacts (TESA), which zeros the artifact window. ' ...
    'interpWin: padding in ms before/after the removed window used for interpolation. ' ...
    'linear interpolation fits a straight line between the boundary samples.'];
s.params = [ ...
    makeParam('interpolation','Method',    '','linear|cubic|pchip', ...
       'Interpolation method. linear is standard for TMS-EEG.', 'type', 'string'), ...
    makeParam('interpWin',    'Pad window','ms','[before after]', ...
       'Data window in ms on each side of the gap used for interpolation.', 'type', 'vector')];
s.requires = req('pop_tesa_interpdata', 'TESA', ...
    'EEGLAB Plugin Manager → search "TESA" (v1.1.1 or later)');
steps(end+1) = s;

%% ---- Find Artifacts EDM (TESA) --------------------------------------
s = blankStep();
s.name = 'Find Artifacts EDM (TESA)';
s.defaults.chanl             = [];
s.defaults.nc                = 30;
s.defaults.sf                = 1000;
s.defaults.comps             = 10;
s.defaults.tmsMuscleThresh   = 10;
s.defaults.tmsMuscleWin      = [11, 50];
s.defaults.tmsMuscleFeedback = 'on';
s.info = ['TESA: Uses "pop_tesa_edm" to find artifactual ICA components automatically ' ...
    'using the Enhanced Deflation Method (EDM). ' ...
    'EDM identifies components with characteristics of TMS-evoked muscle artifacts ' ...
    'by analysing the time window immediately after the pulse. ' ...
    'nc: number of components to decompose ([] = all channels). ' ...
    'comps: number of top components to evaluate. ' ...
    'tmsMuscleThresh: threshold for muscle detection. ' ...
    'tmsMuscleWin: time window for muscle detection in ms.'];
s.params = [ ...
    makeParam('nc',               'Components to find',    '',  'integer or []', ...
       'Number of components to find. [] finds as many as channels allow.', 'type', 'integer'), ...
    makeParam('comps',            'Components to evaluate','',  'integer', ...
       'Number of leading components to screen for artifacts.', 'type', 'integer'), ...
    makeParam('tmsMuscleThresh',  'Muscle threshold',      '',  '[0 Inf]', ...
       'Threshold for TMS-evoked muscle artifact detection.'), ...
    makeParam('tmsMuscleWin',     'Muscle window',         'ms','[tstart tend]', ...
       'Time window for TMS muscle detection after the pulse.', 'type', 'vector'), ...
    makeParam('chanl',            'Channels',              '',  '[] = all', ...
       'Channel indices to include in EDM. [] = all channels.', 'placeholder', '(all channels)', 'type', 'vector')];
s.requires = req('pop_tesa_edm', 'TESA', ...
    'EEGLAB Plugin Manager → search "TESA" (v1.1.1 or later)');
steps(end+1) = s;

%% ---- SSP SIR ---------------------------------------------------------
s = blankStep();
s.name = 'SSP SIR';
s.defaults.artScale = 'automatic';
s.defaults.timeRange= [5, 50];
s.defaults.PC       = {'data', 90};
s.info = ['TESA: Uses "pop_tesa_sspsir" (Signal Space Projection + Source-Informed Reconstruction) ' ...
    'to suppress TMS-evoked muscle artifacts and other large early-latency components. ' ...
    'Works by projecting data away from the principal components of the artifact. ' ...
    'artScale: ''automatic'' estimates the artifact amplitude from the data. ' ...
    'timeRange: window in ms containing the artifact to suppress (e.g. [5 50]). ' ...
    'PC: number of principal components to suppress — {''data'', 90} keeps 90% of variance. ' ...
    'Best applied to data NOT high-pass filtered below 200 Hz.'];
s.params = [ ...
    makeParam('artScale', 'Artifact scale', '','automatic|[value]', ...
       'automatic = estimate from data. Or provide a numeric scale value.', 'type', 'string'), ...
    makeParam('timeRange','Artifact window','ms','[tstart tend]', ...
       'Time window containing the artifact to suppress (e.g. [5 50]).', 'type', 'vector'), ...
    makeParam('PC',       'Variance kept',  '%', '{''data'', percent}', ...
       'Principal components to keep. {''data'',90} = retain 90% of data variance.', 'type', 'string')];
s.requires = req('pop_tesa_sspsir', 'TESA', ...
    'EEGLAB Plugin Manager → search "TESA" (v1.1.1 or later)');
steps(end+1) = s;

%% ---- Median Filter 1D -----------------------------------------------
s = blankStep();
s.name = 'Median Filter 1D';
s.defaults.timeWin    = [-2, 2];
s.defaults.mdorder    = 5;
s.defaults.event_type = 'spike';
s.info = ['TESA: Uses "tesa_filtmedian" to apply a 1-D median filter of specified ' ...
    'order to remove spike and muscle artifacts. ' ...
    'Median filtering replaces each sample with the median of its neighbourhood, ' ...
    'effectively removing sharp spikes without distorting the surrounding waveform. ' ...
    'timeWin: time window in ms around events to filter (t1 <= 0, t2 >= 0). ' ...
    'mdorder: filter order — higher = smoother but may remove real features. ' ...
    'event_type: ''spike'' targets labelled spike events; ''TMS'' targets TMS events.'];
s.params = [ ...
    makeParam('timeWin',   'Time window', 'ms','[t1 t2], t1<=0, t2>=0', ...
       'Window around events to apply the filter. t1 must be <=0, t2 >=0.', 'type', 'vector'), ...
    makeParam('mdorder',   'Filter order','',  'odd integer >= 1', ...
       'Median filter order. 5 is a safe default for spike removal.', 'type', 'integer'), ...
    makeParam('event_type','Event type',  '',  'spike|TMS', ...
       'Event label to target. ''spike'' for spike artifacts, ''TMS'' for TMS pulses.', 'type', 'string')];
s.requires = req('tesa_filtmedian', 'TESA', ...
    'EEGLAB Plugin Manager → search "TESA" (v1.1.1 or later)');
steps(end+1) = s;

%% ---- Extract TEP (TESA) ---------------------------------------------
s = blankStep();
s.name = 'Extract TEP (TESA)';
s.defaults.type        = 'ROI';
s.defaults.elecs       = 'all';
s.defaults.tepName     = [];
s.defaults.pairCorrect = 'on';
s.defaults.ISI         = [];
s.info = ['TESA: Uses "pop_tesa_tepextract" to average across trials and generate ' ...
    'a TMS-evoked potential (TEP). ' ...
    'type: ''ROI'' averages across selected electrodes; ''GMFA'' computes global mean field amplitude. ' ...
    'elecs: electrode labels for ROI extraction (e.g. {''Cz'',''C1'',''C2''}). ''all'' uses all channels. ' ...
    'pairCorrect: for paired-pulse paradigms, subtract the conditioned from the test response. ' ...
    'Run at the end of the pipeline after all cleaning steps.'];
s.params = [ ...
    makeParam('type',       'Extraction type','','ROI|GMFA', ...
       'ROI = average selected electrodes. GMFA = global mean field amplitude.', 'type', 'string'), ...
    makeParam('elecs',      'Electrodes',     '','all or cell of labels', ...
       'Electrodes to include in ROI. ''all'' uses every channel.', 'type', 'string'), ...
    makeParam('tepName',    'TEP label',      '','string or []', ...
       'Name assigned to the extracted TEP (stored in EEG.TEP).', 'placeholder', '(auto-named)', 'type', 'string'), ...
    makeParam('pairCorrect','Pair correction','','on|off', ...
       'Subtract conditioned response from test response (paired-pulse only).', 'type', 'logical'), ...
    makeParam('ISI',       'ISI',            'ms','[0 Inf] or []', ...
       'Inter-stimulus interval for paired-pulse paradigm.', 'placeholder', '(single pulse)', 'type', 'scalar')];
s.requires = req('pop_tesa_tepextract', 'TESA', ...
    'EEGLAB Plugin Manager → search "TESA" (v1.1.1 or later)');
steps(end+1) = s;

%% ---- Find TEP Peaks (TESA) ------------------------------------------
s = blankStep();
s.name = 'Find TEP Peaks (TESA)';
s.defaults.input   = 'ROI';
s.defaults.direction='positive';
s.defaults.peak    = [30 50; 70 90; 180 220];
s.defaults.peakWin = 0;
s.defaults.method  = 'largest';
s.defaults.samples = 5;
s.defaults.tepName = 'TEP';
s.info = ['TESA: Uses "pop_tesa_peakanalysis" to identify peaks in extracted TEP waveforms. ' ...
    'Searches within user-defined time windows for positive or negative peaks. ' ...
    'peak: Nx2 matrix defining search windows [tstart tend] per peak (ms). ' ...
    'Default windows target N30, P60, P180 components. ' ...
    'method: ''largest'' finds the global maximum; ''centre'' finds the centroid. ' ...
    'Run after Extract TEP (TESA).'];
s.params = [ ...
    makeParam('input',    'Input type',   '','ROI|GMFA', ...
       'Match the extraction type used in Extract TEP (TESA).', 'type', 'string'), ...
    makeParam('direction','Peak polarity','','positive|negative', ...
       'Search for positive or negative peaks within each window.', 'type', 'string'), ...
    makeParam('peak',     'Search windows','ms','Nx2 matrix [tstart tend]', ...
       'Time windows to search per peak, e.g. [30 50; 70 90; 180 220].', 'type', 'vector'), ...
    makeParam('method',   'Find method',       '','largest|centre', ...
       'largest = global max in window. centre = amplitude-weighted centroid.', 'type', 'string'), ...
    makeParam('peakWin',  'Peak half-window', 'ms','[0 Inf]', ...
       '0 = single peak sample. >0 = average amplitude over ±peakWin ms around peak.'), ...
    makeParam('samples',  'Smoothing samples','',  'integer >= 1', ...
       'Number of samples for smoothing before peak detection.', 'type', 'integer'), ...
    makeParam('tepName',  'TEP label',        '','string', ...
       'Name of the TEP to analyse (must match the Extract TEP label).', 'type', 'string')];
s.requires = req('pop_tesa_peakanalysis', 'TESA', ...
    'EEGLAB Plugin Manager → search "TESA" (v1.1.1 or later)');
steps(end+1) = s;

%% ---- TEP Peak Output ------------------------------------------------
s = blankStep();
s.name = 'TEP Peak Output';
s.defaults.tepName    = 'R1';
s.defaults.calcType   = 'amplitude';
s.defaults.winType    = 'individual';
s.defaults.averageWin = 5;
s.defaults.fixedPeak  = [];
s.defaults.tablePlot  = 'on';
s.info = ['TESA: Uses "pop_tesa_peakoutput" to extract amplitude and latency ' ...
    'values from identified TEP peaks. ' ...
    'calcType: ''amplitude'' returns peak amplitude; ''area'' returns area under curve. ' ...
    'winType: ''individual'' uses the peak latency per subject; ''fixed'' uses a common window. ' ...
    'averageWin: window size in ms centred on the peak for amplitude averaging. ' ...
    'Results are exported to the MATLAB workspace as a table.'];
s.params = [ ...
    makeParam('tepName',   'TEP label',     '','string', ...
       'Label of the TEP to extract from (must match Extract TEP label).', 'type', 'string'), ...
    makeParam('calcType',  'Measure',       '','amplitude|area', ...
       'amplitude = peak value; area = integral over the window.', 'type', 'string'), ...
    makeParam('winType',   'Window type',   '','individual|fixed', ...
       'individual = window per subject; fixed = common window across subjects.', 'type', 'string'), ...
    makeParam('averageWin','Average window','ms','[0 Inf]', ...
       'Half-width of the window centred on the peak for averaging.'), ...
    makeParam('fixedPeak', 'Fixed peak',   'ms','[t1 t2] or []', ...
       'Fixed time window for output when winType=fixed.', 'placeholder', '(not applicable)', 'type', 'vector'), ...
    makeParam('tablePlot', 'Plot table',  '', 'on|off', ...
       'Display a table of peak results in the MATLAB command window after computation.', 'type', 'logical')];
s.requires = req('pop_tesa_peakoutput', 'TESA', ...
    'EEGLAB Plugin Manager → search "TESA" (v1.1.1 or later)');
steps(end+1) = s;

%% ---- Remove Recording Noise (SOUND) ----------------------------------
s = blankStep();
s.name = 'Remove Recording Noise (SOUND)';
s.defaults.lambdaValue = 0.2;
s.defaults.iter        = 10;
s.info = ['TESA: Uses "pop_tesa_sound" to suppress recording noise using the ' ...
    'SOUND (Source-Informed Optimal Artifact Removal) algorithm. ' ...
    'SOUND uses source-space constraints to separate neural signals from ' ...
    'sensor-level noise. Data are temporarily re-referenced to average during processing. ' ...
    'lambdaValue: regularisation parameter (0.1–1). Smaller = less regularisation. ' ...
    'iter: number of iterations. More iterations = more refined but slower. ' ...
    'Requires channel location information.'];
s.params = [ ...
    makeParam('lambdaValue','Regularisation','','[0 Inf]', ...
       'Regularisation parameter. 0.2 is a good starting point.'), ...
    makeParam('iter',       'Iterations',    '','integer >= 1', ...
       'Number of SOUND iterations. 10 is standard.', 'type', 'integer')];
s.requires = req('pop_tesa_sound', 'TESA', ...
    'EEGLAB Plugin Manager → search "TESA" (v1.1.1 or later)');
steps(end+1) = s;

%% ---- Visualize EEG Data ---------------------------------------------
s = blankStep();
s.name = 'Visualize EEG Data';
s.defaults.state = [1, 1, 1];
s.info = ['EEGLAB: Uses "pop_eegplot" to open an interactive scrolling plot ' ...
    'of the EEG data. Processing pauses until you press OK in the dialog. ' ...
    'Useful for manual inspection at any point in the pipeline. ' ...
    'state: [1 1 1] = show events, scale bars, and DC offset (defaults are fine).'];
s.params = makeParam('state','Display options','','[0|1 0|1 0|1]', ...
    '[events, scale bar, DC offset] — 1=show, 0=hide. Defaults are fine.', 'type', 'vector');
steps(end+1) = s;

%% ---- Manual Command -------------------------------------------------
s = blankStep();
s.name = 'Manual Command';
s.defaults.command     = '';
s.defaults.description = '';
s.info = ['Enter MATLAB command(s) to execute at this point in the pipeline. ' ...
    'The command has access to all EEGLAB workspace variables: ' ...
    'EEG, ALLEEG, CURRENTSET, ALLCOM, and any variables created by prior steps. ' ...
    'Multiple commands: enter one per line. ' ...
    'Use this for custom processing not covered by the built-in steps. ' ...
    'Example: EEG = pop_select(EEG, ''channel'', 1:60);'];
s.params = [ ...
    makeParam('command',    'Command(s)',   '','MATLAB expression(s)', ...
       'MATLAB code to execute. Has access to EEG, ALLEEG, CURRENTSET.', 'type', 'string'), ...
    makeParam('description','Description', '','string', ...
       'Optional label for this step shown in the pipeline log.', 'type', 'string')];
steps(end+1) = s;

cachedSteps = steps;

end % stepRegistry

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Local helpers

function s = blankStep()
% Returns an empty step struct with correct field names.
s = struct('name','','defaults',struct(),'info','','params',struct([]),'requires',struct([]));
end

function r = req(fn, plugin, installNote, fileExt)
% req  Build one dependency requirement struct.
%   fn          - function name to probe with which() (e.g. 'pop_loadbv')
%   plugin      - display name shown in error messages (e.g. 'bva-io')
%   installNote - one-line install instruction for the user
%   fileExt     - (optional) only check when input files have this extension
%                 (e.g. '.vhdr'). Empty string '' means always check.
if nargin < 4; fileExt = ''; end
r = struct('fn', fn, 'plugin', plugin, 'installNote', installNote, 'fileExt', fileExt);
end

function p = makeParam(key, friendlyName, unit, validRange, description, varargin)
% makeParam  Make a parameter metadata struct.
%   Optional name-value pairs: 'placeholder' (shown in UITable for [] values, e.g.
%   '(all channels)') and 'type': scalar (default) | integer | vector | logical | string | stringlist
placeholder = ''; type = 'scalar';
for i = 1:2:numel(varargin)
    switch lower(varargin{i})
        case 'placeholder'; placeholder = varargin{i+1};
        case 'type';        type = varargin{i+1};
    end
end
p = struct('key',key,'friendlyName',friendlyName,'unit',unit, ...
           'validRange',validRange,'description',description, ...
           'placeholder',placeholder,'type',type);
end
